### PR TITLE
Use createIconSet wrapper in createIconSetFromIcoMoon

### PR DESCRIPTION
**Pull request by cruzach**
`createIconSetFromIcoMoon` will fail if you pass in an `expoAssetId` (see [5276](https://github.com/expo/expo/issues/5267))

You **can** pass an `expoAssetId` to `createIconSet`, because the wrapper handles that argument and then proceeds to route to react-native-vector-icon's `createIconSet` method.

I just moved the glyphmap creation logic into the wrapper, and then rerouted to the Expo `createIconSet` wrapper

### CODE REVIEW

**Comment by netpoe** [comment]
This is my case. I updated to SDK 34.0.3 following all of the Upgrade instructions. 

Changing: 

```
const CustomIcon = createIconSetFromIcoMoon(config, "icomoon");
```

to 

```
const CustomIcon = createIconSetFromIcoMoon(config, "icomoon", "../assets/fonts/icomoon.ttf");
```

broke my app. 
I'm continuing to use the previous params until your change is merged.

Hope your PR gets approved quickly. 
Thanks

**Comment by brentvatne** [comment]
looks reasonable, thanks @cruzach

**Comment by netpoe** [comment]
thanks @brentvatne will this update come in a newer `@expo/vector-icons` version? I'm currently at: `10.0.3`

**Comment by brentvatne** [comment]
10.0.4 is released with this

**Comment by netpoe** [comment]
@brentvatne thx. I can confirm it is working now: 

```
const CustomIcon = createIconSetFromIcoMoon(config, "icomoon", "../assets/fonts/icomoon.ttf");
```

**Pull request merged**
