### PR TITLE
Added New Fontisto Icon From react native vector icons

### PR DESCRIPTION
**Pull request by Kaushald4**
Please review changes and merge this pull request
I encountered an error using native-base because it now uses some newly added Fontisto Icon in react native vector icons and at this time @expo-vector-icons don't have Fontisto icon so I have manually added this Fontisto Icon

### CODE REVIEW

**Comment by Kaushald4** [comment]
sorry sorry my mistake I forgot to export fontisto icon from iconsLazy.js file Now it should work fine

**Comment by Kaushald4** [comment]
really sorry for this silly bug I have fixed it Now 🥺

**Comment by juandav** [comment]
build/IconsLazy not found

**Comment by juandav** [comment]
> 
> 
> really sorry for this silly bug I have fixed it Now 🥺

but for some reason it is not working on windows, but it is ok on linux.

**Platforms:**

- [x] Linux
- [ ] Windows

**Solution:**

With Native-base ```>= v2.13.12```
```
 dependencies {
  "expo": "36.0.2",
  "@expo/vector-icons": "Kaushald4/vector-icons#master",
  "native-base": "2.13.12",
  "react-native": "0.62.0",
  "react-native-web": "0.11.7"
}
```

**Comment by raffaeu** [comment]
I tried, this is my package.json, it fails miserably.

```
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.13",
    "expo": "~37.0.3",
    "@expo/vector-icons": "Kaushald4/vector-icons#master",
    "expo-font": "~8.1.0",
    "native-base": "^2.13.12",
```

Then I add this:

```
"postinstall": "cd ./node_modules/@expo && rimraf vector-icons && git clone https://github.com/Kaushald4/vector-icons.git"
```

But when I add the reference as explained here:

```
"@expo/vector-icons": "Kaushald4/vector-icons#master",
```

I get this error, on Windows:

```
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > @expo/vector-icons@10.0.6 prepare C:\Users\raffa\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-b2b280a2
npm ERR! prepareGitDep > expo-module prepare && npm run generate-lazy && npm run copy-vendor

npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep C:\Users\raffa\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-b2b280a2\node_modules\expo-module-scripts\bin\expo-module-prepare:3
npm ERR! prepareGitDep set -eo pipefail
npm ERR! prepareGitDep         ^^^^^^^^
```

**Comment by brentvatne** [comment]
i published this pr in `@expo/vector-icons@10.1.0` :) you can install that version @raffaeu

**Comment by raffaeu** [comment]
> i published this pr in `@expo/vector-icons@10.1.0` :) you can install that version @raffaeu

I can confirm, it now works without workarounds by using the PR

**Comment by shijiezhou1** [comment]
@expo/vector-icons@10.2.0 is working great

**Pull request merged**
