### PR TITLE
Update to react-native-vector-icons@7.0.0

### PR DESCRIPTION
**Pull request by crux153**
This updates `react-native-vector-icons` vendor files to 7.0.0, updating following icons.

- Update IonIcons to 5.0.1 (closing #123)
- Update MaterialCommunityIcons to 5.3.45
- Update FontAwesome 5 to 5.13.0

 Source: [https://github.com/oblador/react-native-vector-icons/releases/tag/v6.7.0](https://github.com/oblador/react-native-vector-icons/releases/tag/v6.7.0)

react-native-vector-icons 7.0.0 removed `Icon.AndroidToolbar` component as it was removed from React Native core, but I don't see any reference to it in this package so I thought it is safe to bump to 7.0.0 instead of 6.7.0. (Correct me if I was wrong)

I've published the modified `@ref/vector-icons` package to npm to use in my project until this PR gets merged, and it seems to work just fine. Sample project under `/website` directory is also working and can be viewed in [https://github.com/crux153/vector-icons/tree/publish](https://github.com/crux153/vector-icons/tree/publish) branch.

### CODE REVIEW

**Comment by LRNZ09** [comment]
This would be really nice for my project too!

**Comment by RealDyllon** [comment]
@crux153 Nice work! How do I get this working on expo bare? I can't use the webpack alias config that you have used in the website. Is there a way to do that in babel.config.js? Couldn't get babel-plugin-module-resolver to get it to work.

**Comment by crux153** [comment]
@RealDyllon I'm just importing it directly in my app instead of modifying webpack config.

```js
import { Ionicons } from "@ref/vector-icons";
```

Haven't tried using babel. What makes you unable to use webpack's alias?

**Comment by brentvatne** [comment]
thanks! i'll try to land the update to 7.0.0 before sdk39 is released

**Comment by nandorojo** [comment]
@crux153 Thank you for this!

@brentvatne Do you know roughly when this might land? Thanks!

**Comment by flyingcircle** [comment]
@brentvatne expo 39 has been released. Is it reasonable to expect this to be merged and released soon?

**Comment by brentvatne** [comment]
hi there! i'll look into it soon, sorry i have had other higher priority work

**Comment by AlberErre** [comment]
@brentvatne that would be great 🙌🏻, waiting for those icons!

**Comment by PoulsQ** [comment]
@brentvatne Having the latest one of MaterialIcon would be great too!! (like coronavirus :p)
Can't wait for you to look at it! Thank. :)

**Comment by pranshuchittora** [comment]
Friendly ping about the status update. Any possibility of getting this merged a bit early?

**Comment by brentvatne** [comment]
@pranshuchittora - feel free to use the fork mentioned earlier in this thread! we plan to roll out an update to @expo/vector-icons with sdk 40 in december

**Pull request closed without merging**
