### PR TITLE
Add Usage to README.md

### PR DESCRIPTION
**Pull request by morenoh149**
Fixes https://github.com/expo/vector-icons/issues/35

### CODE REVIEW

**Comment by incleaf** [comment]
I think it's worth adding https://github.com/expo/vector-icons/issues/38 at the same time.

**Comment by morenoh149** [comment]
@incleaf there is not "Installation" section in the readme. Your addition is different enough to deserve it's own PR. ;)

**Comment by morenoh149** [comment]
bump

**Comment by brentvatne** [comment]
sorry I missed this for a very long time! :O thanks @morenoh149!

**Pull request merged**
