### PR TITLE
Fix margin right

### PR DESCRIPTION
**Pull request by robertonav20**
Set to 0 the margin right of the icon for to fix the position. Actually isn't possible to align the icon into the button

### CODE REVIEW

**Comment by robertonav20** [comment]
Someone can review this pr?

**Comment by brentvatne** [comment]
i pulled this pr locally and ran it and i couldn't see any difference. can you post some screenshots to demonstrate the before and after?

**Comment by robertonav20** [comment]
Here can you see the difference before and after

before

after

As you can see the difference, the icon is filled with that space

**Comment by brentvatne** [comment]
@robertonav20 - where are you seeing that? i must be missing something, i don't see an icon with a blue background anywhere on the site. please share a full page screenshot

**Comment by robertonav20** [comment]
That images are taken from my react native application.
The problem is the "space" at the right of icon not the blue color

**Comment by brentvatne** [comment]
ah i see.

the intention with this library to have the exact same behavior as react-native-vector-icons but use expo-font to load the fonts. if you can convince react-native-vector-icons to land this change, then we will pull it in here too. https://github.com/oblador/react-native-vector-icons/blob/b9f24f9b3a16fa5df8c2a7a6cb1f01b90d49b80d/lib/icon-button.js#L16-L18

thanks for following up on this!

**Pull request closed without merging**
